site_name: dynatrace-aws-platform-monitoring-s3-log-forwarder
site_description: Serverless architecture that forwards logs from Amazon S3 to Dynatrace
docs_dir: .
exclude_docs: |
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  SECURITY.md

nav:
  - Home: README.md
  - Deployment:
      - Deployment Guide: docs/deployment_guide.md
      - Advanced Deployments: docs/advanced_deployments.md
      - Update Guide: docs/update_guide.md
  - Configuration:
      - Log Forwarding: docs/log_forwarding.md
      - Log Processing: docs/log_processing.md
  - Operations:
      - Function Metrics: docs/function_metrics.md
      - Resiliency: docs/resiliency.md
  - Development:
      - Local Testing: docs/development/local_testing.md
      - Build: docs/build.md
      - Layer Publishing Guide: docs/development/layer_publishing_guide.md

plugins:
  - techdocs-core

markdown_extensions:
  - admonition