sonar.projectKey=Dynatrace:dynatrace-aws-platform-monitoring-s3-log-forwarder
sonar.projectName=dynatrace-aws-platform-monitoring-s3-log-forwarder

sonar.sources=src
sonar.tests=tests

sonar.python.version=3.14

sonar.exclusions=**/__pycache__/**,**/*.pyc,dist/**,build/**
